version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - .:/app
      - '/app/node_modules'
    environment:
      - DB_HOST=mysql_server
      - DB_USER=test
      - DB_PASSWORD=secret
      - DB_NAME=ecommerce_react_node
    depends_on:
      - mysql_server

  mysql_server:
    image: mysql:5.7
    volumes:
        - ./mysql:/var/lib/mysql
    environment:
    - MYSQL_DATABASE=ecommerce_react_node
    - MYSQL_USER=test 
    - MYSQL_PASSWORD=secret 
    - MYSQL_ROOT_PASSWORD=root123
  
  e_client:
    build:
      context: ../client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - app